# Generated by Django 2.2.4 on 2019-12-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(max_length=10)),
            ],
        ),
    ]
